project:
  type: book
  title: Statistical Computing
  output-dir: docs
  
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: prac1.qmd
        text: Second page
book:
  chapters:
  - index.qmd
  - prac1.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left

